/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './tutoriales';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import11 from 'ionic-angular/components/navbar/navbar';
import * as import12 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from 'ionic-angular/components/button/button';
import * as import14 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import19 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from 'ionic-angular/components/content/content';
import * as import22 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import24 from '@angular/core/src/linker/view_container';
import * as import25 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from 'ionic-angular/navigation/view-controller';
import * as import29 from 'ionic-angular/components/app/app';
import * as import30 from 'ionic-angular/components/menu/menu-controller';
import * as import31 from 'ionic-angular/components/toolbar/toolbar';
import * as import32 from 'ionic-angular/platform/platform';
import * as import33 from 'ionic-angular/platform/dom-controller';
import * as import34 from 'ionic-angular/platform/keyboard';
import * as import35 from '@angular/core/src/zone/ng_zone';
import * as import36 from 'ionic-angular/components/tabs/tabs';
import * as import37 from 'ionic-angular/gestures/gesture-controller';
import * as import38 from '@angular/core/src/linker/template_ref';
import * as import39 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import40 from 'ionic-angular/components/icon/icon';
import * as import41 from 'ionic-angular/components/menu/menu-toggle';
import * as import42 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import43 from '@angular/common/src/directives/ng_for';
import * as import44 from 'ionic-angular/components/list/list';
import * as import45 from 'ionic-angular/components/item/item';
import * as import46 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import47 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import48 from 'ionic-angular/util/form';
import * as import49 from 'ionic-angular/components/item/item-reorder';
import * as import50 from 'ionic-angular/components/avatar/avatar';
import * as import51 from '@angular/core/src/security';
export class Wrapper_TutorialesPage {
  /*private*/ _eventHandler:Function;
  context:import0.TutorialesPage;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.TutorialesPage(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_TutorialesPage_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_TutorialesPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.TutorialesPage>;
  _TutorialesPage_0_3:Wrapper_TutorialesPage;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TutorialesPage_Host0,renderType_TutorialesPage_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'page-tutoriales',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_TutorialesPage0(this.viewUtils,this,0,this._el_0);
    this._TutorialesPage_0_3 = new Wrapper_TutorialesPage(this.injectorGet(import8.NavController,this.parentIndex),this.injectorGet(import9.NavParams,this.parentIndex));
    this.compView_0.create(this._TutorialesPage_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._TutorialesPage_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.TutorialesPage) && (0 === requestNodeIndex))) { return this._TutorialesPage_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._TutorialesPage_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const TutorialesPageNgFactory:import7.ComponentFactory<import0.TutorialesPage> = new import7.ComponentFactory<import0.TutorialesPage>('page-tutoriales',View_TutorialesPage_Host0,import0.TutorialesPage);
const styles_TutorialesPage:any[] = ([] as any[]);
var renderType_TutorialesPage:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_TutorialesPage,{});
export class View_TutorialesPage0 extends import1.AppView<import0.TutorialesPage> {
  _el_0:any;
  _Header_0_3:import10.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import11.Navbar>;
  _Navbar_2_3:import12.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import13.Button>;
  _Button_4_3:import14.Wrapper_Button;
  _MenuToggle_4_4:import15.Wrapper_MenuToggle;
  _ToolbarItem_4_5:import16.Wrapper_ToolbarItem;
  _query_Button_4_0:import17.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import18.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  compView_9:import1.AppView<import19.ToolbarTitle>;
  _ToolbarTitle_9_3:import20.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  compView_14:import1.AppView<import21.Content>;
  _Content_14_3:import22.Wrapper_Content;
  _text_15:any;
  _el_16:any;
  _List_16_3:import23.Wrapper_List;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _vc_18:import24.ViewContainer;
  _TemplateRef_18_5:any;
  _NgFor_18_6:import25.Wrapper_NgFor;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_TutorialesPage0,renderType_TutorialesPage,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'ion-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._Header_0_3 = new import10.Wrapper_Header(this.parentView.injectorGet(import26.Config,this.parentIndex),new import27.ElementRef(this._el_0),this.renderer,this.parentView.injectorGet(import28.ViewController,this.parentIndex,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'ion-navbar',new import3.InlineArray2(2,'class','toolbar'),(null as any));
    this.compView_2 = new import12.View_Navbar0(this.viewUtils,this,2,this._el_2);
    this._Navbar_2_3 = new import12.Wrapper_Navbar(this.parentView.injectorGet(import29.App,this.parentIndex),this.parentView.injectorGet(import28.ViewController,this.parentIndex,(null as any)),this.parentView.injectorGet(import8.NavController,this.parentIndex,(null as any)),this.parentView.injectorGet(import26.Config,this.parentIndex),new import27.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'ion-button','','menuToggle',''),(null as any));
    this.compView_4 = new import14.View_Button0(this.viewUtils,this,4,this._el_4);
    this._Button_4_3 = new import14.Wrapper_Button('',this.parentView.injectorGet(import26.Config,this.parentIndex),new import27.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_4 = new import15.Wrapper_MenuToggle(this.parentView.injectorGet(import30.MenuController,this.parentIndex),this.parentView.injectorGet(import28.ViewController,this.parentIndex,(null as any)),this._Button_4_3.context,this._Navbar_2_3.context);
    this._ToolbarItem_4_5 = new import16.Wrapper_ToolbarItem(this.parentView.injectorGet(import26.Config,this.parentIndex),new import27.ElementRef(this._el_4),this.renderer,this.parentView.injectorGet(import31.Toolbar,this.parentIndex,(null as any)),this._Navbar_2_3.context);
    this._query_Button_4_0 = new import17.QueryList<any>();
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,(null as any),'ion-icon',new import3.InlineArray4(4,'name','menu','role','img'),(null as any));
    this._Icon_6_3 = new import18.Wrapper_Icon(this.parentView.injectorGet(import26.Config,this.parentIndex),new import27.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_4.create(this._Button_4_3.context);
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,(null as any),'ion-title',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_9 = new import20.View_ToolbarTitle0(this.viewUtils,this,9,this._el_9);
    this._ToolbarTitle_9_3 = new import20.Wrapper_ToolbarTitle(this.parentView.injectorGet(import26.Config,this.parentIndex),new import27.ElementRef(this._el_9),this.renderer,this.parentView.injectorGet(import31.Toolbar,this.parentIndex,(null as any)),this._Navbar_2_3.context);
    this._text_10 = this.renderer.createText((null as any),'Tutoriales',(null as any));
    this.compView_9.create(this._ToolbarTitle_9_3.context);
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    this.compView_2.create(this._Navbar_2_3.context);
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,parentRenderNode,'ion-content',new import3.InlineArray2(2,'padding',''),(null as any));
    this.compView_14 = new import22.View_Content0(this.viewUtils,this,14,this._el_14);
    this._Content_14_3 = new import22.Wrapper_Content(this.parentView.injectorGet(import26.Config,this.parentIndex),this.parentView.injectorGet(import32.Platform,this.parentIndex),this.parentView.injectorGet(import33.DomController,this.parentIndex),new import27.ElementRef(this._el_14),this.renderer,this.parentView.injectorGet(import29.App,this.parentIndex),this.parentView.injectorGet(import34.Keyboard,this.parentIndex),this.parentView.injectorGet(import35.NgZone,this.parentIndex),this.parentView.injectorGet(import28.ViewController,this.parentIndex,(null as any)),this.parentView.injectorGet(import36.Tabs,this.parentIndex,(null as any)));
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,(null as any),'ion-list',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._List_16_3 = new import23.Wrapper_List(this.parentView.injectorGet(import26.Config,this.parentIndex),new import27.ElementRef(this._el_16),this.renderer,this.parentView.injectorGet(import32.Platform,this.parentIndex),this.parentView.injectorGet(import37.GestureController,this.parentIndex),this.parentView.injectorGet(import33.DomController,this.parentIndex));
    this._text_17 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._vc_18 = new import24.ViewContainer(18,16,this,this._anchor_18);
    this._TemplateRef_18_5 = new import38.TemplateRef_(this,18,this._anchor_18);
    this._NgFor_18_6 = new import25.Wrapper_NgFor(this._vc_18.vcRef,this._TemplateRef_18_5,this.parentView.injectorGet(import39.IterableDiffers,this.parentIndex),this.ref);
    this._text_19 = this.renderer.createText(this._el_16,'\n  ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n\n',(null as any));
    this.compView_14.create(this._Content_14_3.context);
    this._text_22 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_4));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import40.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import13.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_3.context; }
    if (((token === import41.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_4.context; }
    if (((token === import42.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_5.context; }
    if (((token === import19.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_3.context; }
    if (((token === import11.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_3.context; }
    if (((token === import31.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import38.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import43.NgFor) && (18 === requestNodeIndex))) { return this._NgFor_18_6.context; }
    if (((token === import44.List) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._List_16_3.context; }
    if (((token === import21.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Content_14_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._Navbar_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    if (this._Button_4_3.ngDoCheck(this,this._el_4,throwOnChange)) { this.compView_4.markAsCheckOnce(); }
    const currVal_4_1_0:any = '';
    this._MenuToggle_4_4.check_menuToggle(currVal_4_1_0,throwOnChange,false);
    this._MenuToggle_4_4.ngDoCheck(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_5.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_6_0_0:any = 'menu';
    this._Icon_6_3.check_name(currVal_6_0_0,throwOnChange,false);
    this._Icon_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_3.ngDoCheck(this,this._el_9,throwOnChange)) { this.compView_9.markAsCheckOnce(); }
    if (this._Content_14_3.ngDoCheck(this,this._el_14,throwOnChange)) { this.compView_14.markAsCheckOnce(); }
    this._List_16_3.ngDoCheck(this,this._el_16,throwOnChange);
    const currVal_18_0_0:any = this.context.herramientas;
    this._NgFor_18_6.check_ngForOf(currVal_18_0_0,throwOnChange,false);
    this._NgFor_18_6.ngDoCheck(this,this._anchor_18,throwOnChange);
    this._vc_18.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_3.context]);
        this._ToolbarItem_4_5.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_3.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MenuToggle_4_4.context.ngAfterContentInit(); }
    }
    this._Navbar_2_3.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this._MenuToggle_4_4.checkHost(this,this.compView_4,this._el_4,throwOnChange);
    this._Icon_6_3.checkHost(this,this,this._el_6,throwOnChange);
    this._Content_14_3.checkHost(this,this.compView_14,this._el_14,throwOnChange);
    this.compView_2.detectChanges(throwOnChange);
    this.compView_4.detectChanges(throwOnChange);
    this.compView_9.detectChanges(throwOnChange);
    this.compView_14.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_18.destroyNestedViews();
    this.compView_2.destroy();
    this.compView_4.destroy();
    this.compView_9.destroy();
    this.compView_14.destroy();
    this._Icon_6_3.ngOnDestroy();
    this._Content_14_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) { cb(this._el_4,ctx); }
    if (((nodeIndex == 2) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 3))) {
      cb(this._text_3,ctx);
      cb(this._text_8,ctx);
      cb(this._el_9,ctx);
      cb(this._text_11,ctx);
    }
    if (((nodeIndex == 4) && (ngContentIndex == 0))) {
      cb(this._text_5,ctx);
      cb(this._el_6,ctx);
      cb(this._text_7,ctx);
    }
    if (((nodeIndex == 9) && (ngContentIndex == 0))) { cb(this._text_10,ctx); }
    if (((nodeIndex == 14) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 14) && (ngContentIndex == 1))) {
      cb(this._text_15,ctx);
      cb(this._el_16,ctx);
      cb(this._text_20,ctx);
      cb(this._text_21,ctx);
    }
    if (((nodeIndex == 14) && (ngContentIndex == 2))) {  }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 18)) { return new View_TutorialesPage1(this.viewUtils,this,18,this._anchor_18,this._vc_18); }
    return (null as any);
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MenuToggle_4_4.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_TutorialesPage1 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import45.Item>;
  _Item_0_3:import46.Wrapper_Item;
  _ItemContent_0_4:import46.Wrapper_ItemContent;
  _query_Label_0_0:import17.QueryList<any>;
  _query_Button_0_1:import17.QueryList<any>;
  _query_Icon_0_2:import17.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Avatar_2_3:import47.Wrapper_Avatar;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import24.ViewContainer) {
    super(View_TutorialesPage1,renderType_TutorialesPage,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_23 = import6.UNINITIALIZED;
    this._expr_24 = import6.UNINITIALIZED;
    this._expr_25 = import6.UNINITIALIZED;
    this._expr_26 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'ion-item',new import3.InlineArray2(2,'class','item item-block'),(null as any));
    this.compView_0 = new import46.View_Item0(this.viewUtils,this,0,this._el_0);
    this._Item_0_3 = new import46.Wrapper_Item(this.parentView.parentView.injectorGet(import48.Form,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import26.Config,this.parentView.parentIndex),new import27.ElementRef(this._el_0),this.renderer,this.parentView.parentView.injectorGet(import49.ItemReorder,this.parentView.parentIndex,(null as any)));
    this._ItemContent_0_4 = new import46.Wrapper_ItemContent();
    this._query_Label_0_0 = new import17.QueryList<any>();
    this._query_Button_0_1 = new import17.QueryList<any>();
    this._query_Icon_0_2 = new import17.QueryList<any>();
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'ion-avatar',new import3.InlineArray2(2,'item-left',''),(null as any));
    this._Avatar_2_3 = new import47.Wrapper_Avatar();
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'img',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,(null as any),'h2',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,(null as any),'h3',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,(null as any),'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_3.context.contentLabel = this._query_Label_0_0.first;
    this.compView_0.create(this._Item_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import50.Avatar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Avatar_2_3.context; }
    if (((token === import45.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Item_0_3.context; }
    if (((token === import45.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._ItemContent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._ItemContent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this._Avatar_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_3.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_3.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_3.context.ngAfterContentInit(); }
    }
    const currVal_23:any = import3.inlineInterpolate(1,'',this.context.$implicit.icono,'');
    if (import3.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import51.SecurityContext.URL,currVal_23));
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = import3.inlineInterpolate(1,'',this.context.$implicit.titulo,'');
    if (import3.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setText(this._text_8,currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = import3.inlineInterpolate(1,'',this.context.$implicit.subtitulo,'');
    if (import3.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setText(this._text_11,currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = import3.inlineInterpolate(1,'',this.context.$implicit.descripcion,'');
    if (import3.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setText(this._text_14,currVal_26);
      this._expr_26 = currVal_26;
    }
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._el_2,ctx); }
    if (((nodeIndex == 0) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 0) && (ngContentIndex == 2))) {
      cb(this._text_1,ctx);
      cb(this._text_6,ctx);
      cb(this._el_7,ctx);
      cb(this._text_9,ctx);
      cb(this._el_10,ctx);
      cb(this._text_12,ctx);
      cb(this._el_13,ctx);
      cb(this._text_15,ctx);
    }
    if (((nodeIndex == 0) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 0) && (ngContentIndex == 4))) {  }
  }
}