/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from 'ionic-angular/index';
import * as import9 from '@angular/common/src/localization';
import * as import10 from 'ionic-angular/util/ionic-error-handler';
import * as import11 from 'ionic-angular/platform/dom-controller';
import * as import12 from 'ionic-angular/components/menu/menu-controller';
import * as import13 from 'ionic-angular/components/app/app';
import * as import14 from 'ionic-angular/gestures/gesture-controller';
import * as import15 from '@angular/core/src/application_init';
import * as import16 from '@angular/core/src/testability/testability';
import * as import17 from '@angular/core/src/application_ref';
import * as import18 from '@angular/core/src/linker/compiler';
import * as import19 from 'ionic-angular/gestures/gesture-config';
import * as import20 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import21 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import22 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import23 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import24 from '@angular/core/src/linker/view_utils';
import * as import25 from '@angular/platform-browser/src/browser/title';
import * as import26 from '@angular/http/src/backends/browser_xhr';
import * as import27 from '@angular/http/src/base_response_options';
import * as import28 from '@angular/http/src/backends/xhr_backend';
import * as import29 from '@angular/http/src/base_request_options';
import * as import30 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import31 from '@angular/forms/src/form_builder';
import * as import32 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import33 from 'ionic-angular/components/alert/alert';
import * as import34 from 'ionic-angular/util/events';
import * as import35 from 'ionic-angular/util/form';
import * as import36 from 'ionic-angular/tap-click/haptic';
import * as import37 from 'ionic-angular/platform/keyboard';
import * as import38 from 'ionic-angular/components/loading/loading';
import * as import39 from '@angular/common/src/location/location';
import * as import40 from 'ionic-angular/components/modal/modal';
import * as import41 from 'ionic-angular/components/picker/picker';
import * as import42 from 'ionic-angular/components/popover/popover';
import * as import43 from 'ionic-angular/tap-click/tap-click';
import * as import44 from 'ionic-angular/components/toast/toast';
import * as import45 from 'ionic-angular/transitions/transition-controller';
import * as import46 from '@angular/core/src/di/injector';
import * as import47 from '../node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as import48 from '../node_modules/ionic-angular/components/alert/alert-component.ngfactory';
import * as import49 from '../node_modules/ionic-angular/components/app/app-root.ngfactory';
import * as import50 from '../node_modules/ionic-angular/components/loading/loading-component.ngfactory';
import * as import51 from '../node_modules/ionic-angular/components/modal/modal-component.ngfactory';
import * as import52 from '../node_modules/ionic-angular/components/picker/picker-component.ngfactory';
import * as import53 from '../node_modules/ionic-angular/components/popover/popover-component.ngfactory';
import * as import54 from '../node_modules/ionic-angular/components/toast/toast-component.ngfactory';
import * as import55 from './app.component.ngfactory';
import * as import56 from '../pages/inicio/inicio.ngfactory';
import * as import57 from '../pages/page2/page2.ngfactory';
import * as import58 from '../pages/payaescuela/payaescuela.ngfactory';
import * as import59 from '../pages/quienes-somos/quienes-somos.ngfactory';
import * as import60 from '../pages/nuestra-mision/nuestra-mision.ngfactory';
import * as import61 from '../pages/nuestra-historia/nuestra-historia.ngfactory';
import * as import62 from '../pages/solicita-visita/solicita-visita.ngfactory';
import * as import63 from '../pages/donativo/donativo.ngfactory';
import * as import64 from '../pages/tutoriales/tutoriales.ngfactory';
import * as import65 from '@angular/core/src/application_tokens';
import * as import66 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import67 from '@angular/platform-browser/src/dom/events/key_events';
import * as import68 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import69 from '@angular/core/src/zone/ng_zone';
import * as import70 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import71 from './app.component';
import * as import72 from '@angular/common/src/location/platform_location';
import * as import73 from '@angular/common/src/location/location_strategy';
import * as import74 from 'ionic-angular/navigation/url-serializer';
import * as import75 from 'ionic-angular/navigation/deep-linker';
import * as import76 from 'ionic-angular/platform/platform-registry';
import * as import77 from 'ionic-angular/platform/platform';
import * as import78 from 'ionic-angular/config/config';
import * as import79 from 'ionic-angular/config/mode-registry';
import * as import80 from 'ionic-angular/transitions/transition-registry';
import * as import81 from '@angular/core/src/console';
import * as import82 from '@angular/core/src/i18n/tokens';
import * as import83 from '@angular/core/src/error_handler';
import * as import84 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import85 from '@angular/platform-browser/src/dom/animation_driver';
import * as import86 from '@angular/core/src/render/api';
import * as import87 from '@angular/core/src/security';
import * as import88 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import89 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import90 from '@angular/http/src/interfaces';
import * as import91 from '@angular/http/src/http';
import * as import92 from 'ionic-angular/components/app/app-root';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _InternalFormsSharedModule_4:import6.InternalFormsSharedModule;
  _FormsModule_5:import7.FormsModule;
  _ReactiveFormsModule_6:import7.ReactiveFormsModule;
  _IonicModule_7:import8.IonicModule;
  _AppModule_8:import1.AppModule;
  __LOCALE_ID_9:any;
  __NgLocalization_10:import9.NgLocaleLocalization;
  _ErrorHandler_11:import10.IonicErrorHandler;
  _ConfigToken_12:any;
  _DOCUMENT_13:any;
  _PlatformConfigToken_14:any;
  _Platform_15:any;
  _Config_16:any;
  _DomController_17:import11.DomController;
  _MenuController_18:import12.MenuController;
  _App_19:import13.App;
  _GestureController_20:import14.GestureController;
  _APP_INITIALIZER_21:any[];
  _ApplicationInitStatus_22:import15.ApplicationInitStatus;
  _Testability_23:import16.Testability;
  _ApplicationRef__24:import17.ApplicationRef_;
  __ApplicationRef_25:any;
  __Compiler_26:import18.Compiler;
  __APP_ID_27:any;
  __HAMMER_GESTURE_CONFIG_28:import19.IonicGestureConfig;
  __EVENT_MANAGER_PLUGINS_29:any[];
  __EventManager_30:import20.EventManager;
  __DomSharedStylesHost_31:import21.DomSharedStylesHost;
  __AnimationDriver_32:any;
  __DomRootRenderer_33:import22.DomRootRenderer_;
  __RootRenderer_34:any;
  __DomSanitizer_35:import23.DomSanitizerImpl;
  __Sanitizer_36:any;
  __ViewUtils_37:import24.ViewUtils;
  __IterableDiffers_38:any;
  __KeyValueDiffers_39:any;
  __SharedStylesHost_40:any;
  __Title_41:import25.Title;
  __BrowserXhr_42:import26.BrowserXhr;
  __ResponseOptions_43:import27.BaseResponseOptions;
  __XSRFStrategy_44:any;
  __XHRBackend_45:import28.XHRBackend;
  __RequestOptions_46:import29.BaseRequestOptions;
  __Http_47:any;
  __RadioControlRegistry_48:import30.RadioControlRegistry;
  __FormBuilder_49:import31.FormBuilder;
  __AppRootToken_50:any;
  __DeepLinkConfigToken_51:any;
  __ActionSheetController_52:import32.ActionSheetController;
  __AlertController_53:import33.AlertController;
  __Events_54:import34.Events;
  __Form_55:import35.Form;
  __Haptic_56:import36.Haptic;
  __Keyboard_57:import37.Keyboard;
  __LoadingController_58:import38.LoadingController;
  __LocationStrategy_59:any;
  __Location_60:import39.Location;
  __ModalController_61:import40.ModalController;
  __PickerController_62:import41.PickerController;
  __PopoverController_63:import42.PopoverController;
  __TapClick_64:import43.TapClick;
  __ToastController_65:import44.ToastController;
  __TransitionController_66:import45.TransitionController;
  __UrlSerializer_67:any;
  __DeepLinker_68:any;
  constructor(parent:import46.Injector) {
    super(parent,[
      import47.ActionSheetCmpNgFactory,
      import48.AlertCmpNgFactory,
      import49.IonicAppNgFactory,
      import50.LoadingCmpNgFactory,
      import51.ModalCmpNgFactory,
      import52.PickerCmpNgFactory,
      import53.PopoverCmpNgFactory,
      import54.ToastCmpNgFactory,
      import55.MyAppNgFactory,
      import55.MyAppNgFactory,
      import56.InicioPageNgFactory,
      import57.Page2NgFactory,
      import58.PayaescuelaPageNgFactory,
      import59.QuienesSomosPageNgFactory,
      import60.NuestraMisionPageNgFactory,
      import61.NuestraHistoriaPageNgFactory,
      import62.SolicitaVisitaPageNgFactory,
      import63.DonativoPageNgFactory,
      import64.TutorialesPageNgFactory,
      import49.IonicAppNgFactory
    ]
    ,[import49.IonicAppNgFactory]);
  }
  get _LOCALE_ID_9():any {
    if ((this.__LOCALE_ID_9 == null)) { (this.__LOCALE_ID_9 = 'en-US'); }
    return this.__LOCALE_ID_9;
  }
  get _NgLocalization_10():import9.NgLocaleLocalization {
    if ((this.__NgLocalization_10 == null)) { (this.__NgLocalization_10 = new import9.NgLocaleLocalization(this._LOCALE_ID_9)); }
    return this.__NgLocalization_10;
  }
  get _ApplicationRef_25():any {
    if ((this.__ApplicationRef_25 == null)) { (this.__ApplicationRef_25 = this._ApplicationRef__24); }
    return this.__ApplicationRef_25;
  }
  get _Compiler_26():import18.Compiler {
    if ((this.__Compiler_26 == null)) { (this.__Compiler_26 = new import18.Compiler()); }
    return this.__Compiler_26;
  }
  get _APP_ID_27():any {
    if ((this.__APP_ID_27 == null)) { (this.__APP_ID_27 = import65._appIdRandomProviderFactory()); }
    return this.__APP_ID_27;
  }
  get _HAMMER_GESTURE_CONFIG_28():import19.IonicGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_28 == null)) { (this.__HAMMER_GESTURE_CONFIG_28 = new import19.IonicGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_28;
  }
  get _EVENT_MANAGER_PLUGINS_29():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_29 == null)) { (this.__EVENT_MANAGER_PLUGINS_29 = [
      new import66.DomEventsPlugin(),
      new import67.KeyEventsPlugin(),
      new import68.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_28)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_29;
  }
  get _EventManager_30():import20.EventManager {
    if ((this.__EventManager_30 == null)) { (this.__EventManager_30 = new import20.EventManager(this._EVENT_MANAGER_PLUGINS_29,this.parent.get(import69.NgZone))); }
    return this.__EventManager_30;
  }
  get _DomSharedStylesHost_31():import21.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_31 == null)) { (this.__DomSharedStylesHost_31 = new import21.DomSharedStylesHost(this._DOCUMENT_13)); }
    return this.__DomSharedStylesHost_31;
  }
  get _AnimationDriver_32():any {
    if ((this.__AnimationDriver_32 == null)) { (this.__AnimationDriver_32 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_32;
  }
  get _DomRootRenderer_33():import22.DomRootRenderer_ {
    if ((this.__DomRootRenderer_33 == null)) { (this.__DomRootRenderer_33 = new import22.DomRootRenderer_(this._DOCUMENT_13,this._EventManager_30,this._DomSharedStylesHost_31,this._AnimationDriver_32,this._APP_ID_27)); }
    return this.__DomRootRenderer_33;
  }
  get _RootRenderer_34():any {
    if ((this.__RootRenderer_34 == null)) { (this.__RootRenderer_34 = import70._createConditionalRootRenderer(this._DomRootRenderer_33,this.parent.get(import70.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_34;
  }
  get _DomSanitizer_35():import23.DomSanitizerImpl {
    if ((this.__DomSanitizer_35 == null)) { (this.__DomSanitizer_35 = new import23.DomSanitizerImpl()); }
    return this.__DomSanitizer_35;
  }
  get _Sanitizer_36():any {
    if ((this.__Sanitizer_36 == null)) { (this.__Sanitizer_36 = this._DomSanitizer_35); }
    return this.__Sanitizer_36;
  }
  get _ViewUtils_37():import24.ViewUtils {
    if ((this.__ViewUtils_37 == null)) { (this.__ViewUtils_37 = new import24.ViewUtils(this._RootRenderer_34,this._Sanitizer_36)); }
    return this.__ViewUtils_37;
  }
  get _IterableDiffers_38():any {
    if ((this.__IterableDiffers_38 == null)) { (this.__IterableDiffers_38 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_38;
  }
  get _KeyValueDiffers_39():any {
    if ((this.__KeyValueDiffers_39 == null)) { (this.__KeyValueDiffers_39 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_39;
  }
  get _SharedStylesHost_40():any {
    if ((this.__SharedStylesHost_40 == null)) { (this.__SharedStylesHost_40 = this._DomSharedStylesHost_31); }
    return this.__SharedStylesHost_40;
  }
  get _Title_41():import25.Title {
    if ((this.__Title_41 == null)) { (this.__Title_41 = new import25.Title()); }
    return this.__Title_41;
  }
  get _BrowserXhr_42():import26.BrowserXhr {
    if ((this.__BrowserXhr_42 == null)) { (this.__BrowserXhr_42 = new import26.BrowserXhr()); }
    return this.__BrowserXhr_42;
  }
  get _ResponseOptions_43():import27.BaseResponseOptions {
    if ((this.__ResponseOptions_43 == null)) { (this.__ResponseOptions_43 = new import27.BaseResponseOptions()); }
    return this.__ResponseOptions_43;
  }
  get _XSRFStrategy_44():any {
    if ((this.__XSRFStrategy_44 == null)) { (this.__XSRFStrategy_44 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_44;
  }
  get _XHRBackend_45():import28.XHRBackend {
    if ((this.__XHRBackend_45 == null)) { (this.__XHRBackend_45 = new import28.XHRBackend(this._BrowserXhr_42,this._ResponseOptions_43,this._XSRFStrategy_44)); }
    return this.__XHRBackend_45;
  }
  get _RequestOptions_46():import29.BaseRequestOptions {
    if ((this.__RequestOptions_46 == null)) { (this.__RequestOptions_46 = new import29.BaseRequestOptions()); }
    return this.__RequestOptions_46;
  }
  get _Http_47():any {
    if ((this.__Http_47 == null)) { (this.__Http_47 = import5.httpFactory(this._XHRBackend_45,this._RequestOptions_46)); }
    return this.__Http_47;
  }
  get _RadioControlRegistry_48():import30.RadioControlRegistry {
    if ((this.__RadioControlRegistry_48 == null)) { (this.__RadioControlRegistry_48 = new import30.RadioControlRegistry()); }
    return this.__RadioControlRegistry_48;
  }
  get _FormBuilder_49():import31.FormBuilder {
    if ((this.__FormBuilder_49 == null)) { (this.__FormBuilder_49 = new import31.FormBuilder()); }
    return this.__FormBuilder_49;
  }
  get _AppRootToken_50():any {
    if ((this.__AppRootToken_50 == null)) { (this.__AppRootToken_50 = import71.MyApp); }
    return this.__AppRootToken_50;
  }
  get _DeepLinkConfigToken_51():any {
    if ((this.__DeepLinkConfigToken_51 == null)) { (this.__DeepLinkConfigToken_51 = (null as any)); }
    return this.__DeepLinkConfigToken_51;
  }
  get _ActionSheetController_52():import32.ActionSheetController {
    if ((this.__ActionSheetController_52 == null)) { (this.__ActionSheetController_52 = new import32.ActionSheetController(this._App_19)); }
    return this.__ActionSheetController_52;
  }
  get _AlertController_53():import33.AlertController {
    if ((this.__AlertController_53 == null)) { (this.__AlertController_53 = new import33.AlertController(this._App_19)); }
    return this.__AlertController_53;
  }
  get _Events_54():import34.Events {
    if ((this.__Events_54 == null)) { (this.__Events_54 = new import34.Events()); }
    return this.__Events_54;
  }
  get _Form_55():import35.Form {
    if ((this.__Form_55 == null)) { (this.__Form_55 = new import35.Form()); }
    return this.__Form_55;
  }
  get _Haptic_56():import36.Haptic {
    if ((this.__Haptic_56 == null)) { (this.__Haptic_56 = new import36.Haptic(this._Platform_15)); }
    return this.__Haptic_56;
  }
  get _Keyboard_57():import37.Keyboard {
    if ((this.__Keyboard_57 == null)) { (this.__Keyboard_57 = new import37.Keyboard(this._Config_16,this._Platform_15,this.parent.get(import69.NgZone),this._DomController_17)); }
    return this.__Keyboard_57;
  }
  get _LoadingController_58():import38.LoadingController {
    if ((this.__LoadingController_58 == null)) { (this.__LoadingController_58 = new import38.LoadingController(this._App_19)); }
    return this.__LoadingController_58;
  }
  get _LocationStrategy_59():any {
    if ((this.__LocationStrategy_59 == null)) { (this.__LocationStrategy_59 = import8.provideLocationStrategy(this.parent.get(import72.PlatformLocation),this.parent.get(import73.APP_BASE_HREF,(null as any)),this._Config_16)); }
    return this.__LocationStrategy_59;
  }
  get _Location_60():import39.Location {
    if ((this.__Location_60 == null)) { (this.__Location_60 = new import39.Location(this._LocationStrategy_59)); }
    return this.__Location_60;
  }
  get _ModalController_61():import40.ModalController {
    if ((this.__ModalController_61 == null)) { (this.__ModalController_61 = new import40.ModalController(this._App_19)); }
    return this.__ModalController_61;
  }
  get _PickerController_62():import41.PickerController {
    if ((this.__PickerController_62 == null)) { (this.__PickerController_62 = new import41.PickerController(this._App_19)); }
    return this.__PickerController_62;
  }
  get _PopoverController_63():import42.PopoverController {
    if ((this.__PopoverController_63 == null)) { (this.__PopoverController_63 = new import42.PopoverController(this._App_19)); }
    return this.__PopoverController_63;
  }
  get _TapClick_64():import43.TapClick {
    if ((this.__TapClick_64 == null)) { (this.__TapClick_64 = new import43.TapClick(this._Config_16,this._Platform_15,this._DomController_17,this._App_19,this.parent.get(import69.NgZone),this._GestureController_20)); }
    return this.__TapClick_64;
  }
  get _ToastController_65():import44.ToastController {
    if ((this.__ToastController_65 == null)) { (this.__ToastController_65 = new import44.ToastController(this._App_19)); }
    return this.__ToastController_65;
  }
  get _TransitionController_66():import45.TransitionController {
    if ((this.__TransitionController_66 == null)) { (this.__TransitionController_66 = new import45.TransitionController(this._Platform_15,this._Config_16)); }
    return this.__TransitionController_66;
  }
  get _UrlSerializer_67():any {
    if ((this.__UrlSerializer_67 == null)) { (this.__UrlSerializer_67 = import74.setupUrlSerializer(this._DeepLinkConfigToken_51)); }
    return this.__UrlSerializer_67;
  }
  get _DeepLinker_68():any {
    if ((this.__DeepLinker_68 == null)) { (this.__DeepLinker_68 = import75.setupDeepLinker(this._App_19,this._UrlSerializer_67,this._Location_60)); }
    return this.__DeepLinker_68;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._InternalFormsSharedModule_4 = new import6.InternalFormsSharedModule();
    this._FormsModule_5 = new import7.FormsModule();
    this._ReactiveFormsModule_6 = new import7.ReactiveFormsModule();
    this._IonicModule_7 = new import8.IonicModule();
    this._AppModule_8 = new import1.AppModule();
    this._ErrorHandler_11 = new import10.IonicErrorHandler();
    this._ConfigToken_12 = (null as any);
    this._DOCUMENT_13 = import4._document();
    this._PlatformConfigToken_14 = import76.providePlatformConfigs();
    this._Platform_15 = import77.setupPlatform(this._DOCUMENT_13,this._PlatformConfigToken_14,this.parent.get(import69.NgZone));
    this._Config_16 = import78.setupConfig(this._ConfigToken_12,this._Platform_15);
    this._DomController_17 = new import11.DomController(this._Platform_15);
    this._MenuController_18 = new import12.MenuController();
    this._App_19 = new import13.App(this._Config_16,this._Platform_15,this._MenuController_18);
    this._GestureController_20 = new import14.GestureController(this._App_19);
    this._APP_INITIALIZER_21 = [
      import79.registerModeConfigs(this._Config_16),
      import80.registerTransitions(this._Config_16),
      import34.setupProvideEvents(this._Platform_15,this._DomController_17),
      import43.setupTapClick(this._Config_16,this._Platform_15,this._DomController_17,this._App_19,this.parent.get(import69.NgZone),this._GestureController_20)
    ]
    ;
    this._ApplicationInitStatus_22 = new import15.ApplicationInitStatus(this._APP_INITIALIZER_21);
    this._Testability_23 = new import16.Testability(this.parent.get(import69.NgZone));
    this._ApplicationRef__24 = new import17.ApplicationRef_(this.parent.get(import69.NgZone),this.parent.get(import81.Console),this,this._ErrorHandler_11,this,this._ApplicationInitStatus_22,this.parent.get(import16.TestabilityRegistry,(null as any)),this._Testability_23);
    return this._AppModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_4; }
    if ((token === import7.FormsModule)) { return this._FormsModule_5; }
    if ((token === import7.ReactiveFormsModule)) { return this._ReactiveFormsModule_6; }
    if ((token === import8.IonicModule)) { return this._IonicModule_7; }
    if ((token === import1.AppModule)) { return this._AppModule_8; }
    if ((token === import82.LOCALE_ID)) { return this._LOCALE_ID_9; }
    if ((token === import9.NgLocalization)) { return this._NgLocalization_10; }
    if ((token === import83.ErrorHandler)) { return this._ErrorHandler_11; }
    if ((token === import78.ConfigToken)) { return this._ConfigToken_12; }
    if ((token === import84.DOCUMENT)) { return this._DOCUMENT_13; }
    if ((token === import76.PlatformConfigToken)) { return this._PlatformConfigToken_14; }
    if ((token === import77.Platform)) { return this._Platform_15; }
    if ((token === import78.Config)) { return this._Config_16; }
    if ((token === import11.DomController)) { return this._DomController_17; }
    if ((token === import12.MenuController)) { return this._MenuController_18; }
    if ((token === import13.App)) { return this._App_19; }
    if ((token === import14.GestureController)) { return this._GestureController_20; }
    if ((token === import15.APP_INITIALIZER)) { return this._APP_INITIALIZER_21; }
    if ((token === import15.ApplicationInitStatus)) { return this._ApplicationInitStatus_22; }
    if ((token === import16.Testability)) { return this._Testability_23; }
    if ((token === import17.ApplicationRef_)) { return this._ApplicationRef__24; }
    if ((token === import17.ApplicationRef)) { return this._ApplicationRef_25; }
    if ((token === import18.Compiler)) { return this._Compiler_26; }
    if ((token === import65.APP_ID)) { return this._APP_ID_27; }
    if ((token === import68.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_28; }
    if ((token === import20.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_29; }
    if ((token === import20.EventManager)) { return this._EventManager_30; }
    if ((token === import21.DomSharedStylesHost)) { return this._DomSharedStylesHost_31; }
    if ((token === import85.AnimationDriver)) { return this._AnimationDriver_32; }
    if ((token === import22.DomRootRenderer)) { return this._DomRootRenderer_33; }
    if ((token === import86.RootRenderer)) { return this._RootRenderer_34; }
    if ((token === import23.DomSanitizer)) { return this._DomSanitizer_35; }
    if ((token === import87.Sanitizer)) { return this._Sanitizer_36; }
    if ((token === import24.ViewUtils)) { return this._ViewUtils_37; }
    if ((token === import88.IterableDiffers)) { return this._IterableDiffers_38; }
    if ((token === import89.KeyValueDiffers)) { return this._KeyValueDiffers_39; }
    if ((token === import21.SharedStylesHost)) { return this._SharedStylesHost_40; }
    if ((token === import25.Title)) { return this._Title_41; }
    if ((token === import26.BrowserXhr)) { return this._BrowserXhr_42; }
    if ((token === import27.ResponseOptions)) { return this._ResponseOptions_43; }
    if ((token === import90.XSRFStrategy)) { return this._XSRFStrategy_44; }
    if ((token === import28.XHRBackend)) { return this._XHRBackend_45; }
    if ((token === import29.RequestOptions)) { return this._RequestOptions_46; }
    if ((token === import91.Http)) { return this._Http_47; }
    if ((token === import30.RadioControlRegistry)) { return this._RadioControlRegistry_48; }
    if ((token === import31.FormBuilder)) { return this._FormBuilder_49; }
    if ((token === import92.AppRootToken)) { return this._AppRootToken_50; }
    if ((token === import74.DeepLinkConfigToken)) { return this._DeepLinkConfigToken_51; }
    if ((token === import32.ActionSheetController)) { return this._ActionSheetController_52; }
    if ((token === import33.AlertController)) { return this._AlertController_53; }
    if ((token === import34.Events)) { return this._Events_54; }
    if ((token === import35.Form)) { return this._Form_55; }
    if ((token === import36.Haptic)) { return this._Haptic_56; }
    if ((token === import37.Keyboard)) { return this._Keyboard_57; }
    if ((token === import38.LoadingController)) { return this._LoadingController_58; }
    if ((token === import73.LocationStrategy)) { return this._LocationStrategy_59; }
    if ((token === import39.Location)) { return this._Location_60; }
    if ((token === import40.ModalController)) { return this._ModalController_61; }
    if ((token === import41.PickerController)) { return this._PickerController_62; }
    if ((token === import42.PopoverController)) { return this._PopoverController_63; }
    if ((token === import43.TapClick)) { return this._TapClick_64; }
    if ((token === import44.ToastController)) { return this._ToastController_65; }
    if ((token === import45.TransitionController)) { return this._TransitionController_66; }
    if ((token === import74.UrlSerializer)) { return this._UrlSerializer_67; }
    if ((token === import75.DeepLinker)) { return this._DeepLinker_68; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__24.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);