/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from 'ionic-angular/platform/platform';
import * as import9 from '@angular/core/src/linker/query_list';
import * as import10 from 'ionic-angular/components/menu/menu';
import * as import11 from '../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import12 from '../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from 'ionic-angular/components/toolbar/toolbar';
import * as import14 from '../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import15 from 'ionic-angular/components/button/button';
import * as import16 from '../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import17 from '../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import18 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import19 from '../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import20 from '../node_modules/ionic-angular/components/menu/menu-close.ngfactory';
import * as import21 from 'ionic-angular/components/content/content';
import * as import22 from '../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import23 from '../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import24 from '@angular/core/src/linker/view_container';
import * as import25 from '../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import26 from 'ionic-angular/components/nav/nav';
import * as import27 from '../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import28 from 'ionic-angular/components/menu/menu-controller';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from 'ionic-angular/config/config';
import * as import31 from 'ionic-angular/platform/keyboard';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from 'ionic-angular/gestures/gesture-controller';
import * as import34 from 'ionic-angular/platform/dom-controller';
import * as import35 from 'ionic-angular/components/app/app';
import * as import36 from 'ionic-angular/navigation/view-controller';
import * as import37 from 'ionic-angular/components/navbar/navbar';
import * as import38 from 'ionic-angular/components/tabs/tabs';
import * as import39 from '@angular/core/src/linker/template_ref';
import * as import40 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import41 from 'ionic-angular/navigation/nav-controller';
import * as import42 from '@angular/core/src/linker/component_factory_resolver';
import * as import43 from 'ionic-angular/transitions/transition-controller';
import * as import44 from 'ionic-angular/navigation/deep-linker';
import * as import45 from 'ionic-angular/components/icon/icon';
import * as import46 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import47 from 'ionic-angular/components/menu/menu-close';
import * as import48 from '@angular/common/src/directives/ng_for';
import * as import49 from 'ionic-angular/components/list/list';
import * as import50 from 'ionic-angular/components/item/item';
import * as import51 from '../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import52 from 'ionic-angular/util/form';
import * as import53 from 'ionic-angular/components/item/item-reorder';
export class Wrapper_MyApp {
  /*private*/ _eventHandler:Function;
  context:import0.MyApp;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.MyApp(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_MyApp_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_MyApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.MyApp>;
  _MyApp_0_3:Wrapper_MyApp;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MyApp_Host0,renderType_MyApp_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_MyApp0(this.viewUtils,this,0,this._el_0);
    this._MyApp_0_3 = new Wrapper_MyApp(this.injectorGet(import8.Platform,this.parentIndex));
    this.compView_0.create(this._MyApp_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._MyApp_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MyApp) && (0 === requestNodeIndex))) { return this._MyApp_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MyApp_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const MyAppNgFactory:import7.ComponentFactory<import0.MyApp> = new import7.ComponentFactory<import0.MyApp>('ng-component',View_MyApp_Host0,import0.MyApp);
const styles_MyApp:any[] = ([] as any[]);
var renderType_MyApp:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_MyApp,{});
export class View_MyApp0 extends import1.AppView<import0.MyApp> {
  _viewQuery_Nav_0:import9.QueryList<any>;
  _el_0:any;
  compView_0:import1.AppView<import10.Menu>;
  _Menu_0_3:import11.Wrapper_Menu;
  _query_Content_0_0:import9.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Header_2_3:import12.Wrapper_Header;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import13.Toolbar>;
  _Toolbar_4_3:import12.Wrapper_Toolbar;
  _text_5:any;
  _el_6:any;
  _ToolbarItem_6_3:import14.Wrapper_ToolbarItem;
  _query_Button_6_0:import9.QueryList<any>;
  _text_7:any;
  _el_8:any;
  compView_8:import1.AppView<import15.Button>;
  _Button_8_3:import16.Wrapper_Button;
  _text_9:any;
  _el_10:any;
  _Icon_10_3:import17.Wrapper_Icon;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  compView_15:import1.AppView<import18.ToolbarTitle>;
  _ToolbarTitle_15_3:import19.Wrapper_ToolbarTitle;
  _text_16:any;
  _el_17:any;
  compView_17:import1.AppView<import18.ToolbarTitle>;
  _ToolbarTitle_17_3:import19.Wrapper_ToolbarTitle;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _ToolbarItem_22_3:import14.Wrapper_ToolbarItem;
  _query_Button_22_0:import9.QueryList<any>;
  _text_23:any;
  _el_24:any;
  compView_24:import1.AppView<import15.Button>;
  _Button_24_3:import16.Wrapper_Button;
  _MenuClose_24_4:import20.Wrapper_MenuClose;
  _text_25:any;
  _el_26:any;
  _Icon_26_3:import17.Wrapper_Icon;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  compView_33:import1.AppView<import21.Content>;
  _Content_33_3:import22.Wrapper_Content;
  _text_34:any;
  _el_35:any;
  _List_35_3:import23.Wrapper_List;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _vc_37:import24.ViewContainer;
  _TemplateRef_37_5:any;
  _NgFor_37_6:import25.Wrapper_NgFor;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  compView_43:import1.AppView<import26.Nav>;
  _Nav_43_3:import27.Wrapper_Nav;
  _text_44:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_MyApp0,renderType_MyApp,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._viewQuery_Nav_0 = new import9.QueryList<any>();
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'ion-menu',new import3.InlineArray2(2,'role','navigation'),(null as any));
    this.compView_0 = new import11.View_Menu0(this.viewUtils,this,0,this._el_0);
    this._Menu_0_3 = new import11.Wrapper_Menu(this.parentView.injectorGet(import28.MenuController,this.parentIndex),new import29.ElementRef(this._el_0),this.parentView.injectorGet(import30.Config,this.parentIndex),this.parentView.injectorGet(import8.Platform,this.parentIndex),this.renderer,this.parentView.injectorGet(import31.Keyboard,this.parentIndex),this.parentView.injectorGet(import32.NgZone,this.parentIndex),this.parentView.injectorGet(import33.GestureController,this.parentIndex),this.parentView.injectorGet(import34.DomController,this.parentIndex),this.parentView.injectorGet(import35.App,this.parentIndex));
    this._query_Content_0_0 = new import9.QueryList<any>();
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'ion-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._Header_2_3 = new import12.Wrapper_Header(this.parentView.injectorGet(import30.Config,this.parentIndex),new import29.ElementRef(this._el_2),this.renderer,this.parentView.injectorGet(import36.ViewController,this.parentIndex,(null as any)));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'ion-toolbar',new import3.InlineArray8(6,'class','toolbar','color','frenzy','no-border-top',''),(null as any));
    this.compView_4 = new import12.View_Toolbar0(this.viewUtils,this,4,this._el_4);
    this._Toolbar_4_3 = new import12.Wrapper_Toolbar(this.parentView.injectorGet(import36.ViewController,this.parentIndex,(null as any)),this.parentView.injectorGet(import30.Config,this.parentIndex),new import29.ElementRef(this._el_4),this.renderer);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,(null as any),'ion-buttons',new import3.InlineArray2(2,'start',''),(null as any));
    this._ToolbarItem_6_3 = new import14.Wrapper_ToolbarItem(this.parentView.injectorGet(import30.Config,this.parentIndex),new import29.ElementRef(this._el_6),this.renderer,this._Toolbar_4_3.context,this.parentView.injectorGet(import37.Navbar,this.parentIndex,(null as any)));
    this._query_Button_6_0 = new import9.QueryList<any>();
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'button',new import3.InlineArray4(4,'icon-only','','ion-button',''),(null as any));
    this.compView_8 = new import16.View_Button0(this.viewUtils,this,8,this._el_8);
    this._Button_8_3 = new import16.Wrapper_Button('',this.parentView.injectorGet(import30.Config,this.parentIndex),new import29.ElementRef(this._el_8),this.renderer);
    this._text_9 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,(null as any),'ion-icon',new import3.InlineArray4(4,'name','content','role','img'),(null as any));
    this._Icon_10_3 = new import17.Wrapper_Icon(this.parentView.injectorGet(import30.Config,this.parentIndex),new import29.ElementRef(this._el_10),this.renderer);
    this._text_11 = this.renderer.createText((null as any),'\n        ',(null as any));
    this.compView_8.create(this._Button_8_3.context);
    this._text_12 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n\n      ',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,(null as any),'ion-title',new import3.InlineArray2(2,'class','favHTitle'),(null as any));
    this.compView_15 = new import19.View_ToolbarTitle0(this.viewUtils,this,15,this._el_15);
    this._ToolbarTitle_15_3 = new import19.Wrapper_ToolbarTitle(this.parentView.injectorGet(import30.Config,this.parentIndex),new import29.ElementRef(this._el_15),this.renderer,this._Toolbar_4_3.context,this.parentView.injectorGet(import37.Navbar,this.parentIndex,(null as any)));
    this._text_16 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,(null as any),'ion-title',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_17 = new import19.View_ToolbarTitle0(this.viewUtils,this,17,this._el_17);
    this._ToolbarTitle_17_3 = new import19.Wrapper_ToolbarTitle(this.parentView.injectorGet(import30.Config,this.parentIndex),new import29.ElementRef(this._el_17),this.renderer,this._Toolbar_4_3.context,this.parentView.injectorGet(import37.Navbar,this.parentIndex,(null as any)));
    this._text_18 = this.renderer.createText((null as any),'SonriApp',(null as any));
    this.compView_17.create(this._ToolbarTitle_17_3.context);
    this._text_19 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n      ',(null as any));
    this.compView_15.create(this._ToolbarTitle_15_3.context);
    this._text_21 = this.renderer.createText((null as any),'\n\n      ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,(null as any),'ion-buttons',new import3.InlineArray2(2,'end',''),(null as any));
    this._ToolbarItem_22_3 = new import14.Wrapper_ToolbarItem(this.parentView.injectorGet(import30.Config,this.parentIndex),new import29.ElementRef(this._el_22),this.renderer,this._Toolbar_4_3.context,this.parentView.injectorGet(import37.Navbar,this.parentIndex,(null as any)));
    this._query_Button_22_0 = new import9.QueryList<any>();
    this._text_23 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'button',new import3.InlineArray8(6,'icon-only','','ion-button','','menuClose',''),(null as any));
    this.compView_24 = new import16.View_Button0(this.viewUtils,this,24,this._el_24);
    this._Button_24_3 = new import16.Wrapper_Button('',this.parentView.injectorGet(import30.Config,this.parentIndex),new import29.ElementRef(this._el_24),this.renderer);
    this._MenuClose_24_4 = new import20.Wrapper_MenuClose(this.parentView.injectorGet(import28.MenuController,this.parentIndex));
    this._text_25 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,(null as any),'ion-icon',new import3.InlineArray8(8,'class','favHIcon','ios','ios-close-circle','md','md-close-circle','role','img'),(null as any));
    this._Icon_26_3 = new import17.Wrapper_Icon(this.parentView.injectorGet(import30.Config,this.parentIndex),new import29.ElementRef(this._el_26),this.renderer);
    this._text_27 = this.renderer.createText((null as any),'\n        ',(null as any));
    this.compView_24.create(this._Button_24_3.context);
    this._text_28 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_4.create(this._Toolbar_4_3.context);
    this._text_30 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,(null as any),'ion-content',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_33 = new import22.View_Content0(this.viewUtils,this,33,this._el_33);
    this._Content_33_3 = new import22.Wrapper_Content(this.parentView.injectorGet(import30.Config,this.parentIndex),this.parentView.injectorGet(import8.Platform,this.parentIndex),this.parentView.injectorGet(import34.DomController,this.parentIndex),new import29.ElementRef(this._el_33),this.renderer,this.parentView.injectorGet(import35.App,this.parentIndex),this.parentView.injectorGet(import31.Keyboard,this.parentIndex),this.parentView.injectorGet(import32.NgZone,this.parentIndex),this.parentView.injectorGet(import36.ViewController,this.parentIndex,(null as any)),this.parentView.injectorGet(import38.Tabs,this.parentIndex,(null as any)));
    this._text_34 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,(null as any),'ion-list',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._List_35_3 = new import23.Wrapper_List(this.parentView.injectorGet(import30.Config,this.parentIndex),new import29.ElementRef(this._el_35),this.renderer,this.parentView.injectorGet(import8.Platform,this.parentIndex),this.parentView.injectorGet(import33.GestureController,this.parentIndex),this.parentView.injectorGet(import34.DomController,this.parentIndex));
    this._text_36 = this.renderer.createText(this._el_35,'\n      ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_35,(null as any));
    this._vc_37 = new import24.ViewContainer(37,35,this,this._anchor_37);
    this._TemplateRef_37_5 = new import39.TemplateRef_(this,37,this._anchor_37);
    this._NgFor_37_6 = new import25.Wrapper_NgFor(this._vc_37.vcRef,this._TemplateRef_37_5,this.parentView.injectorGet(import40.IterableDiffers,this.parentIndex),this.ref);
    this._text_38 = this.renderer.createText(this._el_35,'\n    ',(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n  ',(null as any));
    this.compView_33.create(this._Content_33_3.context);
    this._text_40 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._query_Content_0_0.reset([this._Content_33_3.context]);
    this._Menu_0_3.context.menuContent = this._query_Content_0_0.first;
    this.compView_0.create(this._Menu_0_3.context);
    this._text_41 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_42 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_43 = import3.createRenderElement(this.renderer,parentRenderNode,'ion-nav',new import3.InlineArray2(2,'swipeBackEnabled','false'),(null as any));
    this.compView_43 = new import27.View_Nav0(this.viewUtils,this,43,this._el_43);
    this._Nav_43_3 = new import27.Wrapper_Nav(this.parentView.injectorGet(import36.ViewController,this.parentIndex,(null as any)),this.parentView.injectorGet(import41.NavController,this.parentIndex,(null as any)),this.parentView.injectorGet(import35.App,this.parentIndex),this.parentView.injectorGet(import30.Config,this.parentIndex),this.parentView.injectorGet(import8.Platform,this.parentIndex),this.parentView.injectorGet(import31.Keyboard,this.parentIndex),new import29.ElementRef(this._el_43),this.parentView.injectorGet(import32.NgZone,this.parentIndex),this.renderer,this.parentView.injectorGet(import42.ComponentFactoryResolver,this.parentIndex),this.parentView.injectorGet(import33.GestureController,this.parentIndex),this.parentView.injectorGet(import43.TransitionController,this.parentIndex),this.parentView.injectorGet(import44.DeepLinker,this.parentIndex,(null as any)),this.parentView.injectorGet(import34.DomController,this.parentIndex));
    this.compView_43.create(this._Nav_43_3.context);
    this._text_44 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_24,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_24));
    this._viewQuery_Nav_0.reset([this._Nav_43_3.context]);
    this.context.nav = this._viewQuery_Nav_0.first;
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._anchor_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import45.Icon) && (10 === requestNodeIndex))) { return this._Icon_10_3.context; }
    if (((token === import15.Button) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Button_8_3.context; }
    if (((token === import46.ToolbarItem) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ToolbarItem_6_3.context; }
    if (((token === import18.ToolbarTitle) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._ToolbarTitle_17_3.context; }
    if (((token === import18.ToolbarTitle) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._ToolbarTitle_15_3.context; }
    if (((token === import45.Icon) && (26 === requestNodeIndex))) { return this._Icon_26_3.context; }
    if (((token === import15.Button) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Button_24_3.context; }
    if (((token === import47.MenuClose) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._MenuClose_24_4.context; }
    if (((token === import46.ToolbarItem) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._ToolbarItem_22_3.context; }
    if (((token === import13.Toolbar) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Toolbar_4_3.context; }
    if (((token === import13.Header) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Header_2_3.context; }
    if (((token === import39.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import48.NgFor) && (37 === requestNodeIndex))) { return this._NgFor_37_6.context; }
    if (((token === import49.List) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._List_35_3.context; }
    if (((token === import21.Content) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Content_33_3.context; }
    if (((token === import10.Menu) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Menu_0_3.context; }
    if (((token === import26.Nav) && (43 === requestNodeIndex))) { return this._Nav_43_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this._Nav_43_3.context;
    this._Menu_0_3.check_content(currVal_0_0_0,throwOnChange,false);
    if (this._Menu_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._Header_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_4_0_0:any = 'frenzy';
    this._Toolbar_4_3.check_color(currVal_4_0_0,throwOnChange,false);
    if (this._Toolbar_4_3.ngDoCheck(this,this._el_4,throwOnChange)) { this.compView_4.markAsCheckOnce(); }
    this._ToolbarItem_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    if (this._Button_8_3.ngDoCheck(this,this._el_8,throwOnChange)) { this.compView_8.markAsCheckOnce(); }
    const currVal_10_0_0:any = 'content';
    this._Icon_10_3.check_name(currVal_10_0_0,throwOnChange,false);
    this._Icon_10_3.ngDoCheck(this,this._el_10,throwOnChange);
    if (this._ToolbarTitle_15_3.ngDoCheck(this,this._el_15,throwOnChange)) { this.compView_15.markAsCheckOnce(); }
    if (this._ToolbarTitle_17_3.ngDoCheck(this,this._el_17,throwOnChange)) { this.compView_17.markAsCheckOnce(); }
    this._ToolbarItem_22_3.ngDoCheck(this,this._el_22,throwOnChange);
    if (this._Button_24_3.ngDoCheck(this,this._el_24,throwOnChange)) { this.compView_24.markAsCheckOnce(); }
    const currVal_24_1_0:any = '';
    this._MenuClose_24_4.check_menuClose(currVal_24_1_0,throwOnChange,false);
    this._MenuClose_24_4.ngDoCheck(this,this._el_24,throwOnChange);
    const currVal_26_0_0:any = 'ios-close-circle';
    this._Icon_26_3.check_ios(currVal_26_0_0,throwOnChange,false);
    const currVal_26_0_1:any = 'md-close-circle';
    this._Icon_26_3.check_md(currVal_26_0_1,throwOnChange,false);
    this._Icon_26_3.ngDoCheck(this,this._el_26,throwOnChange);
    if (this._Content_33_3.ngDoCheck(this,this._el_33,throwOnChange)) { this.compView_33.markAsCheckOnce(); }
    this._List_35_3.ngDoCheck(this,this._el_35,throwOnChange);
    const currVal_37_0_0:any = this.context.pages;
    this._NgFor_37_6.check_ngForOf(currVal_37_0_0,throwOnChange,false);
    this._NgFor_37_6.ngDoCheck(this,this._anchor_37,throwOnChange);
    const currVal_43_0_0:any = this.context.rootPage;
    this._Nav_43_3.check_root(currVal_43_0_0,throwOnChange,false);
    const currVal_43_0_1:any = 'false';
    this._Nav_43_3.check_swipeBackEnabled(currVal_43_0_1,throwOnChange,false);
    this._Nav_43_3.ngDoCheck(this,this._el_43,throwOnChange);
    this._vc_37.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_6_0.dirty) {
        this._query_Button_6_0.reset([this._Button_8_3.context]);
        this._ToolbarItem_6_3.context._buttons = this._query_Button_6_0;
        this._query_Button_6_0.notifyOnChanges();
      }
      if (this._query_Button_22_0.dirty) {
        this._query_Button_22_0.reset([this._Button_24_3.context]);
        this._ToolbarItem_22_3.context._buttons = this._query_Button_22_0;
        this._query_Button_22_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_8_3.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_24_3.context.ngAfterContentInit(); }
    }
    this._Toolbar_4_3.checkHost(this,this.compView_4,this._el_4,throwOnChange);
    this._Icon_10_3.checkHost(this,this,this._el_10,throwOnChange);
    this._Icon_26_3.checkHost(this,this,this._el_26,throwOnChange);
    this._Content_33_3.checkHost(this,this.compView_33,this._el_33,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
    this.compView_4.detectChanges(throwOnChange);
    this.compView_8.detectChanges(throwOnChange);
    this.compView_15.detectChanges(throwOnChange);
    this.compView_17.detectChanges(throwOnChange);
    this.compView_24.detectChanges(throwOnChange);
    this.compView_33.detectChanges(throwOnChange);
    this.compView_43.detectChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_43_3.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._vc_37.destroyNestedViews();
    this.compView_0.destroy();
    this.compView_4.destroy();
    this.compView_8.destroy();
    this.compView_15.destroy();
    this.compView_17.destroy();
    this.compView_24.destroy();
    this.compView_33.destroy();
    this.compView_43.destroy();
    this._Icon_10_3.ngOnDestroy();
    this._Icon_26_3.ngOnDestroy();
    this._Content_33_3.ngOnDestroy();
    this._Menu_0_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {
      cb(this._text_1,ctx);
      cb(this._el_2,ctx);
      cb(this._text_32,ctx);
      cb(this._el_33,ctx);
      cb(this._text_40,ctx);
    }
    if (((nodeIndex == 4) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 4) && (ngContentIndex == 1))) { cb(this._el_6,ctx); }
    if (((nodeIndex == 4) && (ngContentIndex == 2))) { cb(this._el_22,ctx); }
    if (((nodeIndex == 4) && (ngContentIndex == 3))) {
      cb(this._text_5,ctx);
      cb(this._text_13,ctx);
      cb(this._text_14,ctx);
      cb(this._el_15,ctx);
      cb(this._text_21,ctx);
      cb(this._text_29,ctx);
    }
    if (((nodeIndex == 8) && (ngContentIndex == 0))) {
      cb(this._text_9,ctx);
      cb(this._el_10,ctx);
      cb(this._text_11,ctx);
    }
    if (((nodeIndex == 15) && (ngContentIndex == 0))) {
      cb(this._text_16,ctx);
      cb(this._el_17,ctx);
      cb(this._text_19,ctx);
      cb(this._text_20,ctx);
    }
    if (((nodeIndex == 17) && (ngContentIndex == 0))) { cb(this._text_18,ctx); }
    if (((nodeIndex == 24) && (ngContentIndex == 0))) {
      cb(this._text_25,ctx);
      cb(this._el_26,ctx);
      cb(this._text_27,ctx);
    }
    if (((nodeIndex == 33) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 33) && (ngContentIndex == 1))) {
      cb(this._text_34,ctx);
      cb(this._el_35,ctx);
      cb(this._text_39,ctx);
    }
    if (((nodeIndex == 33) && (ngContentIndex == 2))) {  }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 37)) { return new View_MyApp1(this.viewUtils,this,37,this._anchor_37,this._vc_37); }
    return (null as any);
  }
  handleEvent_24(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MenuClose_24_4.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_MyApp1 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import50.Item>;
  _Item_0_3:import51.Wrapper_Item;
  _ItemContent_0_4:import51.Wrapper_ItemContent;
  _MenuClose_0_5:import20.Wrapper_MenuClose;
  _query_Label_0_0:import9.QueryList<any>;
  _query_Button_0_1:import9.QueryList<any>;
  _query_Icon_0_2:import9.QueryList<any>;
  _text_1:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import24.ViewContainer) {
    super(View_MyApp1,renderType_MyApp,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_9 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray8(6,'class','item item-block','ion-item','','menuClose',''),(null as any));
    this.compView_0 = new import51.View_Item0(this.viewUtils,this,0,this._el_0);
    this._Item_0_3 = new import51.Wrapper_Item(this.parentView.parentView.injectorGet(import52.Form,this.parentView.parentIndex),this.parentView.parentView.injectorGet(import30.Config,this.parentView.parentIndex),new import29.ElementRef(this._el_0),this.renderer,this.parentView.parentView.injectorGet(import53.ItemReorder,this.parentView.parentIndex,(null as any)));
    this._ItemContent_0_4 = new import51.Wrapper_ItemContent();
    this._MenuClose_0_5 = new import20.Wrapper_MenuClose(this.parentView.parentView.injectorGet(import28.MenuController,this.parentView.parentIndex));
    this._query_Label_0_0 = new import9.QueryList<any>();
    this._query_Button_0_1 = new import9.QueryList<any>();
    this._query_Icon_0_2 = new import9.QueryList<any>();
    this._text_1 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_3.context.contentLabel = this._query_Label_0_0.first;
    this.compView_0.create(this._Item_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import50.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Item_0_3.context; }
    if (((token === import50.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._ItemContent_0_4.context; }
    if (((token === import47.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MenuClose_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this._ItemContent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_0_2_0:any = '';
    this._MenuClose_0_5.check_menuClose(currVal_0_2_0,throwOnChange,false);
    this._MenuClose_0_5.ngDoCheck(this,this._el_0,throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_3.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_3.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_3.context.ngAfterContentInit(); }
    }
    const currVal_9:any = import3.inlineInterpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import3.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setText(this._text_1,currVal_9);
      this._expr_9 = currVal_9;
    }
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 0) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 0) && (ngContentIndex == 2))) { cb(this._text_1,ctx); }
    if (((nodeIndex == 0) && (ngContentIndex == 3))) {  }
    if (((nodeIndex == 0) && (ngContentIndex == 4))) {  }
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MenuClose_0_5.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.openPage(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}