/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './inicio';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import10 from 'ionic-angular/components/navbar/navbar';
import * as import11 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import12 from 'ionic-angular/components/button/button';
import * as import13 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import18 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import20 from 'ionic-angular/components/content/content';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from '@angular/core/src/linker/view_container';
import * as import23 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/components/menu/menu-controller';
import * as import29 from 'ionic-angular/components/toolbar/toolbar';
import * as import30 from 'ionic-angular/platform/platform';
import * as import31 from 'ionic-angular/platform/dom-controller';
import * as import32 from 'ionic-angular/platform/keyboard';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from '@angular/core/src/linker/template_ref';
import * as import36 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import37 from 'ionic-angular/components/icon/icon';
import * as import38 from 'ionic-angular/components/menu/menu-toggle';
import * as import39 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import40 from '@angular/common/src/directives/ng_for';
import * as import41 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import42 from 'ionic-angular/components/card/card';
import * as import43 from '@angular/core/src/security';
export class Wrapper_InicioPage {
  /*private*/ _eventHandler:Function;
  context:import0.InicioPage;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.InicioPage(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_InicioPage_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_InicioPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.InicioPage>;
  _InicioPage_0_3:Wrapper_InicioPage;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_InicioPage_Host0,renderType_InicioPage_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'page-inicio',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_InicioPage0(this.viewUtils,this,0,this._el_0);
    this._InicioPage_0_3 = new Wrapper_InicioPage(this.injectorGet(import8.NavController,this.parentIndex));
    this.compView_0.create(this._InicioPage_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._InicioPage_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.InicioPage) && (0 === requestNodeIndex))) { return this._InicioPage_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._InicioPage_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const InicioPageNgFactory:import7.ComponentFactory<import0.InicioPage> = new import7.ComponentFactory<import0.InicioPage>('page-inicio',View_InicioPage_Host0,import0.InicioPage);
const styles_InicioPage:any[] = ([] as any[]);
var renderType_InicioPage:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_InicioPage,{});
export class View_InicioPage0 extends import1.AppView<import0.InicioPage> {
  _el_0:any;
  _Header_0_3:import9.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import10.Navbar>;
  _Navbar_2_3:import11.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  compView_4:import1.AppView<import12.Button>;
  _Button_4_3:import13.Wrapper_Button;
  _MenuToggle_4_4:import14.Wrapper_MenuToggle;
  _ToolbarItem_4_5:import15.Wrapper_ToolbarItem;
  _query_Button_4_0:import16.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import17.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  compView_9:import1.AppView<import18.ToolbarTitle>;
  _ToolbarTitle_9_3:import19.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  compView_14:import1.AppView<import20.Content>;
  _Content_14_3:import21.Wrapper_Content;
  _text_15:any;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _vc_17:import22.ViewContainer;
  _TemplateRef_17_5:any;
  _NgFor_17_6:import23.Wrapper_NgFor;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_InicioPage0,renderType_InicioPage,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'ion-header',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._Header_0_3 = new import9.Wrapper_Header(this.parentView.injectorGet(import24.Config,this.parentIndex),new import25.ElementRef(this._el_0),this.renderer,this.parentView.injectorGet(import26.ViewController,this.parentIndex,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'ion-navbar',new import3.InlineArray2(2,'class','toolbar'),(null as any));
    this.compView_2 = new import11.View_Navbar0(this.viewUtils,this,2,this._el_2);
    this._Navbar_2_3 = new import11.Wrapper_Navbar(this.parentView.injectorGet(import27.App,this.parentIndex),this.parentView.injectorGet(import26.ViewController,this.parentIndex,(null as any)),this.parentView.injectorGet(import8.NavController,this.parentIndex,(null as any)),this.parentView.injectorGet(import24.Config,this.parentIndex),new import25.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray4(4,'ion-button','','menuToggle',''),(null as any));
    this.compView_4 = new import13.View_Button0(this.viewUtils,this,4,this._el_4);
    this._Button_4_3 = new import13.Wrapper_Button('',this.parentView.injectorGet(import24.Config,this.parentIndex),new import25.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_4 = new import14.Wrapper_MenuToggle(this.parentView.injectorGet(import28.MenuController,this.parentIndex),this.parentView.injectorGet(import26.ViewController,this.parentIndex,(null as any)),this._Button_4_3.context,this._Navbar_2_3.context);
    this._ToolbarItem_4_5 = new import15.Wrapper_ToolbarItem(this.parentView.injectorGet(import24.Config,this.parentIndex),new import25.ElementRef(this._el_4),this.renderer,this.parentView.injectorGet(import29.Toolbar,this.parentIndex,(null as any)),this._Navbar_2_3.context);
    this._query_Button_4_0 = new import16.QueryList<any>();
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,(null as any),'ion-icon',new import3.InlineArray4(4,'name','menu','role','img'),(null as any));
    this._Icon_6_3 = new import17.Wrapper_Icon(this.parentView.injectorGet(import24.Config,this.parentIndex),new import25.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_4.create(this._Button_4_3.context);
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,(null as any),'ion-title',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_9 = new import19.View_ToolbarTitle0(this.viewUtils,this,9,this._el_9);
    this._ToolbarTitle_9_3 = new import19.Wrapper_ToolbarTitle(this.parentView.injectorGet(import24.Config,this.parentIndex),new import25.ElementRef(this._el_9),this.renderer,this.parentView.injectorGet(import29.Toolbar,this.parentIndex,(null as any)),this._Navbar_2_3.context);
    this._text_10 = this.renderer.createText((null as any),'Inicio',(null as any));
    this.compView_9.create(this._ToolbarTitle_9_3.context);
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    this.compView_2.create(this._Navbar_2_3.context);
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,parentRenderNode,'ion-content',new import3.InlineArray2(2,'padding',''),(null as any));
    this.compView_14 = new import21.View_Content0(this.viewUtils,this,14,this._el_14);
    this._Content_14_3 = new import21.Wrapper_Content(this.parentView.injectorGet(import24.Config,this.parentIndex),this.parentView.injectorGet(import30.Platform,this.parentIndex),this.parentView.injectorGet(import31.DomController,this.parentIndex),new import25.ElementRef(this._el_14),this.renderer,this.parentView.injectorGet(import27.App,this.parentIndex),this.parentView.injectorGet(import32.Keyboard,this.parentIndex),this.parentView.injectorGet(import33.NgZone,this.parentIndex),this.parentView.injectorGet(import26.ViewController,this.parentIndex,(null as any)),this.parentView.injectorGet(import34.Tabs,this.parentIndex,(null as any)));
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._vc_17 = new import22.ViewContainer(17,14,this,this._anchor_17);
    this._TemplateRef_17_5 = new import35.TemplateRef_(this,17,this._anchor_17);
    this._NgFor_17_6 = new import23.Wrapper_NgFor(this._vc_17.vcRef,this._TemplateRef_17_5,this.parentView.injectorGet(import36.IterableDiffers,this.parentIndex),this.ref);
    this._text_18 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n',(null as any));
    this.compView_14.create(this._Content_14_3.context);
    this._text_20 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_4));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._text_19,
      this._text_20
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import12.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_3.context; }
    if (((token === import38.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_4.context; }
    if (((token === import39.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_5.context; }
    if (((token === import18.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_3.context; }
    if (((token === import10.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_3.context; }
    if (((token === import29.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import35.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import40.NgFor) && (17 === requestNodeIndex))) { return this._NgFor_17_6.context; }
    if (((token === import20.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Content_14_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this._Navbar_2_3.ngDoCheck(this,this._el_2,throwOnChange);
    if (this._Button_4_3.ngDoCheck(this,this._el_4,throwOnChange)) { this.compView_4.markAsCheckOnce(); }
    const currVal_4_1_0:any = '';
    this._MenuToggle_4_4.check_menuToggle(currVal_4_1_0,throwOnChange,false);
    this._MenuToggle_4_4.ngDoCheck(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_5.ngDoCheck(this,this._el_4,throwOnChange);
    const currVal_6_0_0:any = 'menu';
    this._Icon_6_3.check_name(currVal_6_0_0,throwOnChange,false);
    this._Icon_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_3.ngDoCheck(this,this._el_9,throwOnChange)) { this.compView_9.markAsCheckOnce(); }
    if (this._Content_14_3.ngDoCheck(this,this._el_14,throwOnChange)) { this.compView_14.markAsCheckOnce(); }
    const currVal_17_0_0:any = this.context.items;
    this._NgFor_17_6.check_ngForOf(currVal_17_0_0,throwOnChange,false);
    this._NgFor_17_6.ngDoCheck(this,this._anchor_17,throwOnChange);
    this._vc_17.detectChangesInNestedViews(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_3.context]);
        this._ToolbarItem_4_5.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_3.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MenuToggle_4_4.context.ngAfterContentInit(); }
    }
    this._Navbar_2_3.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this._MenuToggle_4_4.checkHost(this,this.compView_4,this._el_4,throwOnChange);
    this._Icon_6_3.checkHost(this,this,this._el_6,throwOnChange);
    this._Content_14_3.checkHost(this,this.compView_14,this._el_14,throwOnChange);
    this.compView_2.detectChanges(throwOnChange);
    this.compView_4.detectChanges(throwOnChange);
    this.compView_9.detectChanges(throwOnChange);
    this.compView_14.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_17.destroyNestedViews();
    this.compView_2.destroy();
    this.compView_4.destroy();
    this.compView_9.destroy();
    this.compView_14.destroy();
    this._Icon_6_3.ngOnDestroy();
    this._Content_14_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) { cb(this._el_4,ctx); }
    if (((nodeIndex == 2) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 2))) {  }
    if (((nodeIndex == 2) && (ngContentIndex == 3))) {
      cb(this._text_3,ctx);
      cb(this._text_8,ctx);
      cb(this._el_9,ctx);
      cb(this._text_11,ctx);
    }
    if (((nodeIndex == 4) && (ngContentIndex == 0))) {
      cb(this._text_5,ctx);
      cb(this._el_6,ctx);
      cb(this._text_7,ctx);
    }
    if (((nodeIndex == 9) && (ngContentIndex == 0))) { cb(this._text_10,ctx); }
    if (((nodeIndex == 14) && (ngContentIndex == 0))) {  }
    if (((nodeIndex == 14) && (ngContentIndex == 1))) {
      cb(this._text_15,ctx);
      cb(this._text_16,ctx);
      cb(this._vc_17.nativeElement,ctx);
      this._vc_17.visitNestedViewRootNodes(cb,ctx);
      cb(this._text_18,ctx);
      cb(this._text_19,ctx);
    }
    if (((nodeIndex == 14) && (ngContentIndex == 2))) {  }
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 17)) { return new View_InicioPage1(this.viewUtils,this,17,this._anchor_17,this._vc_17); }
    return (null as any);
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MenuToggle_4_4.handleEvent(eventName,$event) && result);
    return result;
  }
}
class View_InicioPage1 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import41.Wrapper_Card;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import22.ViewContainer) {
    super(View_InicioPage1,renderType_InicioPage,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_11 = import6.UNINITIALIZED;
    this._expr_12 = import6.UNINITIALIZED;
    this._expr_13 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'ion-card',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._Card_0_3 = new import41.Wrapper_Card(this.parentView.parentView.injectorGet(import24.Config,this.parentView.parentIndex),new import25.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'img',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','card-title'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','card-subtitle'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Card_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Card_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_11:any = import3.inlineInterpolate(1,'',this.context.$implicit.imagen,'');
    if (import3.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import43.SecurityContext.URL,currVal_11));
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = import3.inlineInterpolate(1,'',this.context.$implicit.titulo,'');
    if (import3.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_5,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = import3.inlineInterpolate(1,'',this.context.$implicit.subtitulo,'');
    if (import3.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setText(this._text_8,currVal_13);
      this._expr_13 = currVal_13;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.open(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}